[package]
name = "asroute"
description = "Interpret traceroute output to show names of ASN traversed"
version = "0.1.0"
authors = ["Steven Pack <steven.pack.code@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
cymrust = "0.3.4"